export { default as Home } from "./home.jsx"
export { default as AllPage } from "./AllPage.jsx"
export { default as Detail } from "./Detail"
export { default as Movies } from "./Movies.jsx"
export { default as TvShows } from "./TvShows.jsx"
export { default as Login } from "./Login.jsx"